//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminPMB
    {
        public long PMBId { get; set; }
        public string AttachedFileName { get; set; }
        public string AttachedFileActualName { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> CreatedFor { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string ModifiedFromIP { get; set; }
        public string CreatedByUserType { get; set; }
        public Nullable<long> StrataBoardId { get; set; }
    }
}
