//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailServer
    {
        public int Id { get; set; }
        public string EmailServer { get; set; }
        public string NetworkUserId { get; set; }
        public string NetworkUserPassword { get; set; }
        public string SenderDisplayName { get; set; }
        public string FromEmail { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
