//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForum
    {
        public tblForum()
        {
            this.tblFlagComments = new HashSet<tblFlagComment>();
            this.tblForumReplies = new HashSet<tblForumReply>();
        }
    
        public long TopicId { get; set; }
        public string Topic { get; set; }
        public string TopicContent { get; set; }
        public string UploadedFileName { get; set; }
        public string UploadedFileActualName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> StratasBoardId { get; set; }
        public Nullable<bool> IsFlagged { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<tblFlagComment> tblFlagComments { get; set; }
        public virtual ICollection<tblForumReply> tblForumReplies { get; set; }
    }
}
