//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlagComment
    {
        public long Id { get; set; }
        public Nullable<long> TopicId { get; set; }
        public Nullable<long> ReplyId { get; set; }
        public string Message { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual tblForum tblForum { get; set; }
        public virtual tblForumReply tblForumReply { get; set; }
    }
}
