//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPollQuestion
    {
        public tblPollQuestion()
        {
            this.tblPollAnswers = new HashSet<tblPollAnswer>();
            this.tblPollOptions = new HashSet<tblPollOption>();
        }
    
        public long PollId { get; set; }
        public string PollHeader { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> StrataBoardId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedFromIP { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<tblPollAnswer> tblPollAnswers { get; set; }
        public virtual ICollection<tblPollOption> tblPollOptions { get; set; }
    }
}
