//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationRequest
    {
        public long QuotationId { get; set; }
        public string RequesterName { get; set; }
        public string RequesterEmailId { get; set; }
        public Nullable<bool> IsShowEmail { get; set; }
        public Nullable<long> DisciplineId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedFromIP { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
