//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReminder
    {
        public tblReminder()
        {
            this.tblReminderDetails = new HashSet<tblReminderDetail>();
        }
    
        public long ReminderId { get; set; }
        public string ReminderSubject { get; set; }
        public string ReminderNote { get; set; }
        public string SmsText { get; set; }
        public Nullable<int> Occurrence { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> StratasBoardId { get; set; }
    
        public virtual ICollection<tblReminderDetail> tblReminderDetails { get; set; }
    }
}
