//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStratasBoard
    {
        public tblStratasBoard()
        {
            this.tblUserClients = new HashSet<tblUserClient>();
        }
    
        public long StratasBoardId { get; set; }
        public string StratasBoardName { get; set; }
        public string PortalLink { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedFromIP { get; set; }
        public Nullable<int> Status { get; set; }
        public string RequestPortalLink { get; set; }
        public string RequestMessage { get; set; }
        public Nullable<System.DateTime> RequestCreatedOn { get; set; }
        public Nullable<int> RequestCounter { get; set; }
        public Nullable<long> RequestCreatedBy { get; set; }
        public string BuildingName { get; set; }
    
        public virtual ICollection<tblUserClient> tblUserClients { get; set; }
    }
}
