//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduleMeetingInvite
    {
        public long MeetingInviteId { get; set; }
        public Nullable<long> MeetingId { get; set; }
        public Nullable<long> UserClientId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
