//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserClient
    {
        public long UserClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<long> StratasBoardId { get; set; }
        public string RoleName { get; set; }
        public string Position { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<System.DateTime> LeaseCommenceDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public string UnitNumber { get; set; }
        public string PremiseType { get; set; }
        public int Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedFromIP { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CurrentLogin { get; set; }
        public bool IsProfileComplete { get; set; }
        public bool IsEmailNotification { get; set; }
        public bool IsSMSNotification { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tblStratasBoard tblStratasBoard { get; set; }
    }
}
