//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserBookingRequest
    {
        public long BookingRequestId { get; set; }
        public long UserClientId { get; set; }
        public Nullable<int> CommonAreaId { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Reason { get; set; }
        public int Status { get; set; }
        public Nullable<int> AdminStatus { get; set; }
        public string AdminRemark { get; set; }
        public Nullable<long> AdminUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> StratasBoardId { get; set; }
    }
}
