//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRequest
    {
        public int RequestId { get; set; }
        public int UserClientId { get; set; }
        public string RequestTitle { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Details { get; set; }
        public int Status { get; set; }
        public string StatusRemark { get; set; }
        public Nullable<long> StatusUpdateBy { get; set; }
        public Nullable<System.DateTime> StatusUpdateOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> StratasBoardId { get; set; }
    }
}
