//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public long VendorId { get; set; }
        public string VendorName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public string OtherDisciplineName { get; set; }
        public string MobileNumber { get; set; }
        public string CompanyBrief { get; set; }
        public string TradeAndBusinessFile { get; set; }
        public string ActualTradeAndBusinessFile { get; set; }
        public string ImageFile { get; set; }
        public string ActualImageFile { get; set; }
        public Nullable<int> AdminApproval { get; set; }
        public string Remark { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedFromIp { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedFromIP { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Pwd_Reset_Req_Date { get; set; }
        public Nullable<int> Pwd_Reset_Req_Status { get; set; }
    }
}
