//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetFlaggedMessage
    {
        public long Id { get; set; }
        public Nullable<long> TopicId { get; set; }
        public Nullable<long> ReplyId { get; set; }
        public Nullable<long> AutoId { get; set; }
        public string ForumMessageType { get; set; }
        public string Message { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedTime { get; set; }
        public string CreatedDateTime { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string CreatedFromIP { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatorName { get; set; }
        public string CreatorEmailId { get; set; }
    }
}
