//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetForumListReply
    {
        public long ReplyId { get; set; }
        public long TopicId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedTime { get; set; }
        public string CreatedDateTime { get; set; }
        public string CreatedFromIP { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<bool> IsFlagged { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CreatedByName { get; set; }
    }
}
