//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratasFair.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetMaintenanceSchedule
    {
        public long MaintenanceScheduleId { get; set; }
        public Nullable<long> StratasBoardId { get; set; }
        public Nullable<int> CommonAreaId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string CommonAreaName { get; set; }
    }
}
